/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViagensIndexRouteImport } from './routes/viagens.index'
import { Route as ViagensIdRouteImport } from './routes/viagens.$id'

const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensIndexRoute = ViagensIndexRouteImport.update({
  id: '/viagens/',
  path: '/viagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensIdRoute = ViagensIdRouteImport.update({
  id: '/viagens/$id',
  path: '/viagens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/viagens/$id': typeof ViagensIdRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/viagens/$id': typeof ViagensIdRoute
  '/viagens': typeof ViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/viagens/$id': typeof ViagensIdRoute
  '/viagens/': typeof ViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/contato' | '/viagens/$id' | '/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/contato' | '/viagens/$id' | '/viagens'
  id: '__root__' | '/' | '/auth' | '/contato' | '/viagens/$id' | '/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  ViagensIdRoute: typeof ViagensIdRoute
  ViagensIndexRoute: typeof ViagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/': {
      id: '/viagens/'
      path: '/viagens'
      fullPath: '/viagens/'
      preLoaderRoute: typeof ViagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens/$id': {
      id: '/viagens/$id'
      path: '/viagens/$id'
      fullPath: '/viagens/$id'
      preLoaderRoute: typeof ViagensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  ViagensIdRoute: ViagensIdRoute,
  ViagensIndexRoute: ViagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
